    # Generated by Django 3.1.1 on 2020-09-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srijaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eddr',
            new_name='eaddr',
        ),
    ]
